[tool.poetry]
name = "text2heximage"
version = "1.0.0"
description = ""
authors = ["dipokal <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
opencv-python = "^4.5.2"
Pillow = "^9.0.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
